Class {
	#name : #MyClassTask7,
	#superclass : #MyClassTask6,
	#category : #'ClassBlueprint-Scenarios'
}

{ #category : #initialization }
MyClassTask7 >> initialize [ 
	super initialize.
	class1 method10
]

{ #category : #accessing }
MyClassTask7 >> method1 [ 
	class1 method11
]

{ #category : #'as yet unclassified' }
MyClassTask7 >> method10: aValue [
	class1 method10: aValue.
	class1 method14: aValue.
	class1 method2
]

{ #category : #'as yet unclassified' }
MyClassTask7 >> method14: aValue [ 
	class1 method14: aValue
]
