Class {
	#name : #MyClassTask0,
	#superclass : #Object,
	#instVars : [
		'att0'
	],
	#category : #'ClassBlueprint-Scenarios'
}

{ #category : #accessing }
MyClassTask0 >> att0 [
	^ att0
]

{ #category : #accessing }
MyClassTask0 >> att0: aValue [
	 att0 := aValue
]

{ #category : #'as yet unclassified' }
MyClassTask0 >> method15 [
]

{ #category : #'as yet unclassified' }
MyClassTask0 >> method17 [

]

{ #category : #accessing }
MyClassTask0 >> method2 [
]

{ #category : #'as yet unclassified' }
MyClassTask0 >> method4 [ 

]

{ #category : #'as yet unclassified' }
MyClassTask0 >> method9 [
]
