Class {
	#name : #MyClassTask1,
	#superclass : #MyClassTask0,
	#instVars : [
		'att1',
		'att2',
		'att3',
		'att4',
		'att5'
	],
	#category : #'ClassBlueprint-Scenarios'
}

{ #category : #accessing }
MyClassTask1 >> att1 [ 
	^ att1
]

{ #category : #accessing }
MyClassTask1 >> att1: aValue [
	att1 := aValue
]

{ #category : #accessing }
MyClassTask1 >> att2 [ 
	^ att2
]

{ #category : #accessing }
MyClassTask1 >> att2: aValue [
	att1 := aValue
]

{ #category : #accessing }
MyClassTask1 >> att3 [ 
	^ att3
]

{ #category : #accessing }
MyClassTask1 >> att3: aValue [
	att3 := aValue
]

{ #category : #accessing }
MyClassTask1 >> att4 [
	^ att4
]

{ #category : #accessing }
MyClassTask1 >> att4: aValue [
	att4 := aValue
]

{ #category : #accessing }
MyClassTask1 >> att5 [
	^ att5
]

{ #category : #accessing }
MyClassTask1 >> att5: aValue [
	att5 := aValue
]

{ #category : #'as yet unclassified' }
MyClassTask1 >> method3 [ 	
	self subclassResponsibility 
]

{ #category : #accessing }
MyClassTask1 >> method5 [
	att0

	
]

{ #category : #'as yet unclassified' }
MyClassTask1 >> method6 [ 
	self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
MyClassTask1 >> method7 [ 	
	self subclassResponsibility 
]

{ #category : #'as yet unclassified' }
MyClassTask1 >> method8 [
	self subclassResponsibility 
	
]
